import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import WidthWrapper from "@/components/WidthWrapper";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const nunito = Nunito({ subsets: ["latin"], variable: "--font-nunito" });

export const metadata: Metadata = {
   title: "Pet Nest Nepal",
   description: "Generated by Pet Nest Nepal",
   icons: {
      icon: "/favicon_io/logo.svg",
   },
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${inter.className} ${nunito.className} antialiased`}>
            <Navbar />
            <WidthWrapper>
               <main>{children}</main>
               <Toaster />
            </WidthWrapper>
            <Footer />
         </body>
      </html>
   );
}
